# SPDX-FileCopyrightText: 2025 IDSec Solutions
#
# SPDX-License-Identifier: CC0-1.0

version = 1

# Main project files
[[annotations]]
path = [
    "CHANGELOG.md",
    "REUSE.toml",
    "README.md",
    "pom.xml",
    "**/*.cddl",
    "docs/element-list",
    "docs/DEVELOPMENT.md",
    "renovate.json",
    "jreleaser.yml",
    "**/*/resources/**/*.json",
    "docs/**/*.html",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Digg - Agency for Digital Government"
SPDX-License-Identifier = "CC0-1.0"

